// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Razor_EF_Power.Models;

public partial class Order
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public int ClientId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public virtual Client Client { get; set; }

    public virtual Product Product { get; set; }
}